## Installing Packages, Loading Libraries

In [1]:
install.packages("foreign")
install.packages("Synth")
install.packages("dplyr")
install.packages("gridExtra")
install.packages("tidyverse") 
install.packages("lubridate")
install.packages("tree")
install.packages("Matching")
install.packages("boot")
install.packages("randomForest")
install.packages("arm")
install.packages("ggplot2")
install.packages("cobalt")
library(cobalt)
library(sm)
library(tidyverse) # for data manipulation and visualization
library(lubridate)
library(tree)
library(Matching)
library(boot)
library(randomForest)
library(arm)
library(ggplot2)
library(cobalt)
library(foreign) 
library(splines)
library(grid)
library (dplyr)
library (xtable)
library(lmtest)
library(Synth)
library(gridextra)

Warning message:
"package 'foreign' is not available (for R version 3.6.1)"

package 'Synth' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'dplyr' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'gridExtra' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'tidyverse' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'lubridate' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'tree' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'Matching' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'boot' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'randomForest' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'arm' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'ggplot2' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages
package 'cobalt' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jacob\AppData\Local\Temp\RtmpC87cAy\downloaded_packages

Warning message:
"package 'cobalt' was built under R version 3.6.3" cobalt (Version 4.2.4, Build Date: 2020-11-05 17:30:21 UTC)
Warning message:
"package 'sm' was built under R version 3.6.3"Package 'sm', version 2.2-5.6: type help(sm) for summary information
Warning message:
"package 'tidyverse' was built under R version 3.6.3"-- Attaching packages --------------------------------------- tidyverse 1.3.0 --
v ggplot2 3.3.2     v purrr   0.3.4
v tibble  3.0.3     v dplyr   1.0.2
v tidyr   1.1.2     v stringr 1.4.0
v readr   1.4.0     v forcats 0.5.0
Warning message:
"package 'ggplot2' was built under R version 3.6.3"Warning message:
"package 'tibble' was built under R version 3.6.3"Warning message:
"package 'tidyr' was built under R version 3.6.3"Warning message:
"package 'readr' was built under R version 3.6.3"Warning message:
"package 'purrr' was built under R version 3.6.3"Warning message:
"package 'dplyr' was built under R version 3.6.3"Warning message:
"package 'stringr' was built under R version 3.6.3"Warning message:
"package 'forcats' was built under R version 3.6.3"-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
Warning message:
"package 'lubridate' was built under R version 3.6.3"
Attaching package: 'lubridate'

The following objects are masked from 'package:base':

    date, intersect, setdiff, union

Warning message:
"package 'tree' was built under R version 3.6.3"Registered S3 method overwritten by 'tree':
  method     from
  print.tree cli
Warning message:
"package 'Matching' was built under R version 3.6.3"Loading required package: MASS
Warning message:
"package 'MASS' was built under R version 3.6.3"
Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select

The following object is masked from 'package:sm':

    muscle

##
##  Matching (Version 4.9-7, Build Date: 2020-02-05)
##  See http://sekhon.berkeley.edu/matching for additional documentation.
##  Please cite software as:
##   Jasjeet S. Sekhon. 2011. ``Multivariate and Propensity Score Matching
##   Software with Automated Balance Optimization: The Matching package for R.''
##   Journal of Statistical Software, 42(7): 1-52.
##

Warning message:
"package 'boot' was built under R version 3.6.3"
Attaching package: 'boot'

The following object is masked from 'package:sm':

    dogs

Warning message:
"package 'randomForest' was built under R version 3.6.3"randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.

Attaching package: 'randomForest'

The following object is masked from 'package:dplyr':

    combine

The following object is masked from 'package:ggplot2':

    margin

Warning message:
"package 'arm' was built under R version 3.6.3"Loading required package: Matrix
Warning message:
"package 'Matrix' was built under R version 3.6.3"
Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

Loading required package: lme4
Warning message:
"package 'lme4' was built under R version 3.6.3"

ERROR: Error: package or namespace load failed for 'arm' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'foreign'

## Import All Data

In [9]:
alldata <- read.csv("C:\\Users\\jacob\\Downloads\\Personal\\2001_Table1ALL.csv")
replicationdata <- read.csv("C:\\Users\\jacob\\Downloads\\Personal\\Table 2 Replication Data.csv")
extensiondata <- read.csv("C:\\Users\\jacob\\Downloads\\Personal\\Table 2 Extension Data.csv")
homicide<- read.csv("https://raw.githubusercontent.com/thetruejacob/Final-Project/master/data/homicide_suicide%20(outcome)/cdc_homicide_all.csv")
firearms <- read.csv("https://raw.githubusercontent.com/thetruejacob/Final-Project/master/data/matching-data.csv")
#which(is.na(alldata)) # The which() function returns the positions with missing values in your vector
#which(is.na(replicationdata)) # The which() function returns the positions with missing values in your vector
#which(is.na(extensiondata)) # The which() function returns the positions with missing values in your vector
alldata1 <- na.omit(alldata)
replicationdata1 <- na.omit(replicationdata)
extensiondata1 <- na.omit(extensiondata)
head(alldata1)
head(replicationdata1)
head(extensiondata1)
tail(replicationdata1)
tail(extensiondata1)

  MonYear    Year MonthNo Deaths Treatment Effective Pop      StdPop   Time
1 Jan., 1999 1999 1       49     1         0         15759421 157.5942 1
2 Feb., 1999 1999 2       41     1         0         15759421 157.5942 2
3 Mar., 1999 1999 3       50     1         0         15759421 157.5942 3
4 Apr., 1999 1999 4       42     1         0         15759421 157.5942 4
5 May, 1999  1999 5       46     1         0         15759421 157.5942 5
6 Jun., 1999 1999 6       49     1         0         15759421 157.5942 6
  Trend OrigData Cause Data.Table Characteristic
1 0     1        Combo Table1     All
2 0     1        Combo Table1     All
3 0     1        Combo Table1     All
4 0     1        Combo Table1     All
5 0     1        Combo Table1     All
6 0     1        Combo Table1     All

  State MonYear    Year MonthNo Characteristic Deaths Cause
1 FL    Jan., 1999 1999 1       20-34          24     Firearm Homicide
2 FL    Feb., 1999 1999 2       20-34          20     Firearm Homicide
3 FL    Mar., 1999 1999 3       20-34          24     Firearm Homicide
4 FL    Apr., 1999 1999 4       20-34          23     Firearm Homicide
5 FL    May, 1999  1999 5       20-34          24     Firearm Homicide
6 FL    Jun., 1999 1999 6       20-34          28     Firearm Homicide
  Treatment Population
1 1         2958306
2 1         2958306
3 1         2958306
4 1         2958306
5 1         2958306
6 1         2958306

  State MonYear    Year MonthNo Characteristic Deaths Cause       Treatment
1 FL    Jan., 1999 1999 1       35 and over    15     All Firearm 1
2 FL    Feb., 1999 1999 2       35 and over    15     All Firearm 1
3 FL    Mar., 1999 1999 3       35 and over    20     All Firearm 1
4 FL    Apr., 1999 1999 4       35 and over    13     All Firearm 1
5 FL    May, 1999  1999 5       35 and over    17     All Firearm 1
6 FL    Jun., 1999 1999 6       35 and over    11     All Firearm 1
  Population
1 8867116
2 8867116
3 8867116
4 8867116
5 8867116
6 8867116

     State MonYear    Year MonthNo Characteristic    Deaths Cause
8851 FL    Jul., 2016 2016  7      Hispanic Any Race 14     All Firearm
8852 FL    Aug., 2016 2016  8      Hispanic Any Race 12     All Firearm
8853 FL    Sep., 2016 2016  9      Hispanic Any Race 11     All Firearm
8854 FL    Oct., 2016 2016 10      Hispanic Any Race 15     All Firearm
8855 FL    Nov., 2016 2016 11      Hispanic Any Race 13     All Firearm
8856 FL    Dec., 2016 2016 12      Hispanic Any Race 15     All Firearm
     Treatment Population
8851 1         5126975
8852 1         5126975
8853 1         5126975
8854 1         5126975
8855 1         5126975
8856 1         5126975

     State MonYear    Year MonthNo Characteristic Deaths Cause   Treatment
9067 FL    Jul., 2016 2016  7      White          270    Suicide 1
9068 FL    Aug., 2016 2016  8      White          254    Suicide 1
9069 FL    Sep., 2016 2016  9      White          245    Suicide 1
9070 FL    Oct., 2016 2016 10      White          247    Suicide 1
9071 FL    Nov., 2016 2016 11      White          250    Suicide 1
9072 FL    Dec., 2016 2016 12      White          229    Suicide 1
     Population
9067 15996473
9068 15996473
9069 15996473
9070 15996473
9071 15996473
9072 15996473

## Checking some Aspects

In [ ]:
glimpse(synth.data) #Check the Latest Year the 
tail(synth.data)
synth.tab() #compare the treatment and the synthetic control units across the predictors

## Other Analyses

In [10]:
subset1 <- subset(extensiondata1, Treatment == "1")
head(subset1) #In the State of Florida , everyone is in The Treatment Group

subset2 <- subset(extensiondata1, Cause == "Firearm Homicide")
subset3 <- subset(extensiondata1, Characteristic == "Hispanic Any Race")
subset4 <- subset(extensiondata1, Characteristic == "White")
subset5 <- subset(extensiondata1, Characteristic == "African-American")
NumFirearm <- sapply(subset2, NROW)
NumHisp <- sapply(subset3, NROW)
NumWhite <- sapply(subset4, NROW)
NumAfrican <- sapply(subset5, NROW)
NumFirearm
NumHisp
NumWhite
NumAfrican

  State MonYear    Year MonthNo Characteristic Deaths Cause       Treatment
1 FL    Jan., 1999 1999 1       35 and over    15     All Firearm 1
2 FL    Feb., 1999 1999 2       35 and over    15     All Firearm 1
3 FL    Mar., 1999 1999 3       35 and over    20     All Firearm 1
4 FL    Apr., 1999 1999 4       35 and over    13     All Firearm 1
5 FL    May, 1999  1999 5       35 and over    17     All Firearm 1
6 FL    Jun., 1999 1999 6       35 and over    11     All Firearm 1
  Population
1 8867116
2 8867116
3 8867116
4 8867116
5 8867116
6 8867116

         State        MonYear           Year        MonthNo Characteristic
          1720           1720           1720           1720           1720
        Deaths          Cause      Treatment     Population
          1720           1720           1720           1720

         State        MonYear           Year        MonthNo Characteristic
           630            630            630            630            630
        Deaths          Cause      Treatment     Population
           630            630            630            630

         State        MonYear           Year        MonthNo Characteristic
           864            864            864            864            864
        Deaths          Cause      Treatment     Population
           864            864            864            864

         State        MonYear           Year        MonthNo Characteristic
             0              0              0              0              0
        Deaths          Cause      Treatment     Population
             0              0              0              0

In [11]:
#All DCeaths Combined
print(paste("The Average Deaths of All States Combined is:", mean(alldata1$Deaths))) #To find the Average 
print(paste("Median No. of Deaths in All States is:", median(alldata1$Deaths))) #The Median Data.
print(paste("Average Number of Deaths in Florida is:", mean(extensiondata1$Deaths))) #The Median Data.
print(paste("Median Number of Deaths in Florida is:", median(extensiondata1$Deaths))) #The Median Data.
print(paste("Lower Quartile of Florida Deaths:", quantile(extensiondata1$Deaths, 0.25))) #Finding The Lower Quartile
print(paste("Lower Quartile of All Deaths Deaths:", quantile(alldata1$Deaths, 0.25))) #Finding The Lower Quartile
print(paste("Upper Quartile of Florida Deaths:", quantile(extensiondata1$Deaths, 0.75))) #Finding The Lower Quartile
print(paste("Upper Quartile of All Deaths Deaths:", quantile(alldata1$Deaths, 0.75))) #Finding The Lower Quartile

[1] "The Average Deaths of All States Combined is: 320.428020069471"
[1] "Median No. of Deaths in All States is: 138"
[1] "Average Number of Deaths in Florida is: 55.5031627906977"
[1] "Median Number of Deaths in Florida is: 38"
[1] "Lower Quartile of Florida Deaths: 24"
[1] "Lower Quartile of All Deaths Deaths: 97"
[1] "Upper Quartile of Florida Deaths: 61"
[1] "Upper Quartile of All Deaths Deaths: 279"

In [12]:
#Analyses For Homicides
# Subset Data
allhom <-subset(alldata1, Cause=="AllHomicide")
Florida1<-subset(allhom)
Control1 <- subset(allhom, Treatment ==0)


# Mean Counts For All States and FL 
print(paste("The Average Deaths OF fl Monthly is:",mean(Florida1$Deaths[Florida1$Effective==0]))) ##Florida before
print(paste("The Average Deaths of FL Monthly after Pass of Laws is:",mean(Florida1$Deaths[Florida1$Effective==1]))) ##Florida after
print(paste("The Average Deaths of All States Combined is:",mean(Control1$Deaths[Control1$Effective==0]))) ##Control States before
print(paste("The Average Deaths of All States Combined  Monthly after Pass of Laws is:",mean(Control1$Deaths[Control1$Effective==1]))) ##Control States after

[1] "The Average Deaths OF fl Monthly is: 135.335403726708"
[1] "The Average Deaths of FL Monthly after Pass of Laws is: 141.192592592593"
[1] "The Average Deaths of All States Combined is: 189.4125"
[1] "The Average Deaths of All States Combined  Monthly after Pass of Laws is: 182.614814814815"

In [13]:
#Analyses For All Firearm
# Subset Data
allhom <-subset(alldata1, Cause=="FirearmHomicide")
Florida1<-subset(allhom)
Control1 <- subset(allhom, Treatment ==0)


# Mean Counts For All States and FL 
print(paste("The Average Deaths OF fl Monthly is:",mean(Florida1$Deaths[Florida1$Effective==0]))) ##Florida before
print(paste("The Average Deaths of FL Monthly after Pass of Laws is:",mean(Florida1$Deaths[Florida1$Effective==1]))) ##Florida after
print(paste("The Average Deaths of All States Combined is:",mean(Control1$Deaths[Control1$Effective==0]))) ##Control States before
print(paste("The Average Deaths of All States Combined  Monthly after Pass of Laws is:",mean(Control1$Deaths[Control1$Effective==1]))) ##Control States after

[1] "The Average Deaths OF fl Monthly is: 82.6975308641975"
[1] "The Average Deaths of FL Monthly after Pass of Laws is: 95.6851851851852"
[1] "The Average Deaths of All States Combined is: 116.333333333333"
[1] "The Average Deaths of All States Combined  Monthly after Pass of Laws is: 120.525925925926"

## Checking Weights

In [14]:


repallhom <- subset(alldata1, Cause=="AllHomicide" & Year < 2015)
allhomtop<-repallhom[1:224,]
allhomtbottom <- repallhom[225:383,]
Sept2001 <- cbind("Sept.,2001", 2001,9,189.4, 0,0,46161275, 461.6128,30,0,1,"AllHomicide","Table1","All",.41)
colnames(Sept2001)<- colnames(repallhom)
allhomtop <- rbind(allhomtop, Sept2001)
repallhom <- rbind(allhomtop,allhomtbottom)
repallhom <- transform(repallhom, StdPop = as.numeric(StdPop), Deaths = as.numeric(Deaths), Year = as.numeric(Year),
                       Treatment = as.numeric(Treatment), Pop = as.numeric(Pop), Time = as.numeric(Time), 
                       Trend = as.numeric(Trend), Rate = as.numeric(Rate), MonthNo = as.numeric(MonthNo))


# create matrices from panel data that provide inputs for synth()
dataprep.out<-
  dataprep(
   foo = repallhom ,
   predictors= c("MonYear", "MonthNo",  "Treatment", "Effective", "Pop", "StdPop", "Time", 
 "Trend", "OrigData", "Cause", "Data.Table"
                 ),
   predictors.op = "mean",
   dependent = "Deaths",
   unit.variable = "Characteristic",
   time.variable = "Year",
   special.predictors = list(
      list("Deaths", 1991, "mean"),
      list("Deaths", 1985, "mean"),
      list("Deaths", 1980, "mean")
                            ),
   treatment.identifier = NULL,
   controls.identifier = NULL,
   time.predictors.prior = c(1999:2004),
   time.optimize.ssr = c(1999:2005),
   unit.names.variable = "name",
   time.plot = 1999:2011
   )

## run the synth command to identify the weights
## that create the best possible synthetic 
## control unit for the treated.
synth.out <- synth(dataprep.out)

## there are two ways to summarize the results
## we can either access the output from synth.out directly
round(synth.out$solution.w,2)
# contains the unit weights or
synth.out$solution.v 
## contains the predictor weights.

ERROR: Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent

In [15]:
repallhom

     MonYear    Year MonthNo Deaths Treatment Effective Pop      StdPop   Time
1297 Jan., 1999 1999  1      75     1         0         15759421 157.5942  1
1298 Feb., 1999 1999  2      80     1         0         15759421 157.5942  2
1299 Mar., 1999 1999  3      84     1         0         15759421 157.5942  3
1300 Apr., 1999 1999  4      67     1         0         15759421 157.5942  4
1301 May, 1999  1999  5      84     1         0         15759421 157.5942  5
1302 Jun., 1999 1999  6      81     1         0         15759421 157.5942  6
1303 Jul., 1999 1999  7      95     1         0         15759421 157.5942  7
1304 Aug., 1999 1999  8      59     1         0         15759421 157.5942  8
1305 Sep., 1999 1999  9      78     1         0         15759421 157.5942  9
1306 Oct., 1999 1999 10      93     1         0         15759421 157.5942 10
1307 Nov., 1999 1999 11      69     1         0         15759421 157.5942 11
1308 Dec., 1999 1999 12      99     1         0         15759421 157.5942 12
1309 Jan., 2000 2000  1      92     1         0         16047515 160.4752 13
1310 Feb., 2000 2000  2      74     1         0         16047515 160.4752 14
1311 Mar., 2000 2000  3      72     1         0         16047515 160.4752 15
1312 Apr., 2000 2000  4      77     1         0         16047515 160.4752 16
1313 May, 2000  2000  5      92     1         0         16047515 160.4752 17
1314 Jun., 2000 2000  6      70     1         0         16047515 160.4752 18
1315 Jul., 2000 2000  7      84     1         0         16047515 160.4752 19
1316 Aug., 2000 2000  8      79     1         0         16047515 160.4752 20
1317 Sep., 2000 2000  9      69     1         0         16047515 160.4752 21
1318 Oct., 2000 2000 10      74     1         0         16047515 160.4752 22
1319 Nov., 2000 2000 11      71     1         0         16047515 160.4752 23
1320 Dec., 2000 2000 12      83     1         0         16047515 160.4752 24
1321 Jan., 2001 2001  1      87     1         0         16356966 163.5697 25
1322 Feb., 2001 2001  2      72     1         0         16356966 163.5697 26
1323 Mar., 2001 2001  3      73     1         0         16356966 163.5697 27
1324 Apr., 2001 2001  4      78     1         0         16356966 163.5697 28
1325 May, 2001  2001  5      81     1         0         16356966 163.5697 29
1326 Jun., 2001 2001  6      77     1         0         16356966 163.5697 30
...  ...        ...  ...     ...    ...       ...       ...      ...      ...
1674 Jul., 2012 2012  7      236    0         1         48243129 482.4313 161
1675 Aug., 2012 2012  8      179    0         1         48243129 482.4313 162
1676 Sep., 2012 2012  9      184    0         1         48243129 482.4313 163
1677 Oct., 2012 2012 10      172    0         1         48243129 482.4313 164
1678 Nov., 2012 2012 11      188    0         1         48243129 482.4313 165
1679 Dec., 2012 2012 12      180    0         1         48243129 482.4313 166
1680 Jan., 2013 2013  1      167    0         1         48455783 484.5578 167
1681 Feb., 2013 2013  2      138    0         1         48455783 484.5578 168
1682 Mar., 2013 2013  3      147    0         1         48455783 484.5578 169
1683 Apr., 2013 2013  4      152    0         1         48455783 484.5578 170
1684 May, 2013  2013  5      200    0         1         48455783 484.5578 171
1685 Jun., 2013 2013  6      168    0         1         48455783 484.5578 172
1686 Jul., 2013 2013  7      197    0         1         48455783 484.5578 173
1687 Aug., 2013 2013  8      199    0         1         48455783 484.5578 174
1688 Sep., 2013 2013  9      166    0         1         48455783 484.5578 175
1689 Oct., 2013 2013 10      187    0         1         48455783 484.5578 176
1690 Nov., 2013 2013 11      164    0         1         48455783 484.5578 177
1691 Dec., 2013 2013 12      201    0         1         48455783 484.5578 178
1692 Jan., 2014 2014  1      151    0         1         48627233 486.2723 179
1693 Feb., 2014 2014  2      123    0         1         48627233 486.2723 180
1694 Mar., 2014 2014  3      143    0         1         48627233 486.2723 181
1695 Apr., 2014 2014  4      146    0         1         48627233 486.2723 182
1696 May, 2014  2014  5      174    0         1         48627233 486.2723 183
1697 Jun., 2014 2014  6      193    0         1         48627233 486.2723 184
1698 Jul., 2014 2014  7      167    0         1         48627233 486.2723 185
1699 Aug., 2014 2014  8      164    0         1         48627233 486.2723 186
1700 Sep., 2014 2014  9      166    0         1         48627233 486.2723 187
1701 Oct., 2014 2014 10      183    0         1         48627233 486.2723 188
1702 Nov., 2014 2014 11      178    0         1         48627233 486.2723 189
1703 Dec., 2014 2014 12      163    0         1         48627233 486.2723 190
     Trend OrigData Cause       Data.Table Characteristic
1297 0     1        AllHomicide Table1     All
1298 0     1        AllHomicide Table1     All
1299 0     1        AllHomicide Table1     All
1300 0     1        AllHomicide Table1     All
1301 0     1        AllHomicide Table1     All
1302 0     1        AllHomicide Table1     All
1303 0     1        AllHomicide Table1     All
1304 0     1        AllHomicide Table1     All
1305 0     1        AllHomicide Table1     All
1306 0     1        AllHomicide Table1     All
1307 0     1        AllHomicide Table1     All
1308 0     1        AllHomicide Table1     All
1309 0     1        AllHomicide Table1     All
1310 0     1        AllHomicide Table1     All
1311 0     1        AllHomicide Table1     All
1312 0     1        AllHomicide Table1     All
1313 0     1        AllHomicide Table1     All
1314 0     1        AllHomicide Table1     All
1315 0     1        AllHomicide Table1     All
1316 0     1        AllHomicide Table1     All
1317 0     1        AllHomicide Table1     All
1318 0     1        AllHomicide Table1     All
1319 0     1        AllHomicide Table1     All
1320 0     1        AllHomicide Table1     All
1321 0     1        AllHomicide Table1     All
1322 0     1        AllHomicide Table1     All
1323 0     1        AllHomicide Table1     All
1324 0     1        AllHomicide Table1     All
1325 0     1        AllHomicide Table1     All
1326 0     1        AllHomicide Table1     All
...  ...   ...      ...         ...        ...
1674  82   1        AllHomicide Table1     All
1675  83   1        AllHomicide Table1     All
1676  84   1        AllHomicide Table1     All
1677  85   1        AllHomicide Table1     All
1678  86   1        AllHomicide Table1     All
1679  87   1        AllHomicide Table1     All
1680  88   1        AllHomicide Table1     All
1681  89   1        AllHomicide Table1     All
1682  90   1        AllHomicide Table1     All
1683  91   1        AllHomicide Table1     All
1684  92   1        AllHomicide Table1     All
1685  93   1        AllHomicide Table1     All
1686  94   1        AllHomicide Table1     All
1687  95   1        AllHomicide Table1     All
1688  96   1        AllHomicide Table1     All
1689  97   1        AllHomicide Table1     All
1690  98   1        AllHomicide Table1     All
1691  99   1        AllHomicide Table1     All
1692 100   1        AllHomicide Table1     All
1693 101   1        AllHomicide Table1     All
1694 102   1        AllHomicide Table1     All
1695 103   1        AllHomicide Table1     All
1696 104   1        AllHomicide Table1     All
1697 105   1        AllHomicide Table1     All
1698 106   1        AllHomicide Table1     All
1699 107   1        AllHomicide Table1     All
1700 108   1        AllHomicide Table1     All
1701 109   1        AllHomicide Table1     All
1702 110   1        AllHomicide Table1     All
1703 111   1        AllHomicide Table1     All

In [16]:
#Analyses For Suicides
# Subset Data
allhom <-subset(alldata1, Cause=="Suicide")
Florida1<-subset(allhom)
Control1 <- subset(allhom, Treatment ==0)


# Mean Counts For All States and FL 
print(paste("The Average Deaths OF fl Monthly is:",mean(Florida1$Deaths[Florida1$Effective==0]))) ##Florida before
print(paste("The Average Deaths of FL Monthly after Pass of Laws is:",mean(Florida1$Deaths[Florida1$Effective==1]))) ##Florida after
print(paste("The Average Deaths of All States Combined is:",mean(Control1$Deaths[Control1$Effective==0]))) ##Control States before
print(paste("The Average Deaths of All States Combined  Monthly after Pass of Laws is:",mean(Control1$Deaths[Control1$Effective==1]))) ##Control States after

[1] "The Average Deaths OF fl Monthly is: 251.222222222222"
[1] "The Average Deaths of FL Monthly after Pass of Laws is: 314.92962962963"
[1] "The Average Deaths of All States Combined is: 314.185185185185"
[1] "The Average Deaths of All States Combined  Monthly after Pass of Laws is: 391.651851851852"

In [ ]:

alldata <- read.csv("C:\\Users\\jacob\\Downloads\\Personal\\2001_Table1ALL.csv")
repallhom <- subset(alldata, Cause=="AllHomicide" & Year < 2015)

##Sept 2001 was removed from the analysis but is added back in to graph
allhomtop<-repallhom[1:224,]
allhomtbottom <- repallhom[225:383,]

##Spet 2001 was given the mean monthly count and rate in the before period 
Sept2001 <- cbind("Sept.,2001", 2001,9,189.4, 0,0,46161275, 461.6128,30,0,1,"AllHomicide","Table1","All",.41)
colnames(Sept2001)<- colnames(repallhom)
allhomtop <- rbind(allhomtop, Sept2001)
repallhom <- rbind(allhomtop,allhomtbottom)
repallhom <- transform(repallhom, StdPop = as.numeric(StdPop), Deaths = as.numeric(Deaths), Year = as.numeric(Year),
                       Treatment = as.numeric(Treatment), Pop = as.numeric(Pop), Time = as.numeric(Time), 
                       Trend = as.numeric(Trend), Rate = as.numeric(Rate), MonthNo = as.numeric(MonthNo))

# Setup variables
repallhom$Level <- c(rep(0,81),rep(1,111),rep(0,81),rep(1,111))
repallhom$Time <- c(rep(c(1:192), 2))
repallhom$Trend <- rep(c(rep(0,81), 1:111),2)
repallhom$TXtime <- repallhom$Treatment * repallhom$Time
repallhom$TXlevel <- repallhom$Treatment * repallhom$Level
repallhom$TXtrend <- repallhom$Treatment * repallhom$Trend
repallhom_crappy <- glm(Rate ~ offset(log(StdPop)) + Time + Level + harmonic(MonthNo,2,12), 
                        family=quasipoisson, data=repallhom)
repallhom.mod <- with(repallhom, Deaths/StdPop)
repallhom.datanew <- data.frame(StdPop=mean(repallhom$StdPop),
                                Level=rep(c(0,1), c(819,1101)),
                                Time = 1:1920/10,
                                MonthNo = rep(1:120/10, 16))

# Models
repallhom.pred1 <- predict(repallhom_crappy,type="response",repallhom.datanew)/mean(repallhom$StdPop)
repallhom.pred2 <- predict(repallhom_crappy,type="response",transform(repallhom,MonthNo=4.8))/mean(repallhom$StdPop)

repallhom_linear <- glm(Rate ~ offset(log(StdPop)) + Time + Treatment + Level +  
                          TXtime + TXlevel, 
                        family=quasipoisson, data=repallhom)
repallhom_harmonic <- glm(Rate ~ offset(log(StdPop)) + Time + Treatment + Level + 
                            TXtime + TXlevel + harmonic(MonthNo,2,12), 
                          family=quasipoisson, data=repallhom)

###Plot for replication all homicide 
plot(repfirehom$Time[1:192],repfirehom.mod[1:192],
     type="n",
     ylim=c(0,1),
     frame.plot=F,
     ylab="Deaths per 100,000",
     xlab="Year",
     xaxt="n",
     las=2)
axis(1,at=0:15*12+6,tick=T,labels=1999:2014) 
rect(81,0,192,1, col=grey(0.9),border=F)
points(repallhom$Time[1:192],repallhom.mod[1:192],
       col="darkorange2",
       pch=20)
points(repallhom$Time[193:384],repallhom.mod[193:384],
       col="dodgerblue4",
       pch=20)
lines(repallhom$Time[1:81], fitted(repallhom_linear)[1:81], col="darkorange",lty=5)
lines(repallhom$Time[1:81], fitted(repallhom_harmonic)[1:81], col="darkorange",lwd=2)
lines(repallhom$Time[82:192], fitted(repallhom_linear)[82:192], col="darkorange",lty=5)
lines(repallhom$Time[82:192], fitted(repallhom_harmonic)[82:192], col="darkorange",lwd=2)
lines(repallhom$Time[193:273], fitted(repallhom_linear)[193:273], col="dodgerblue4",lty=5)
lines(repallhom$Time[193:273], fitted(repallhom_harmonic)[193:273], col="dodgerblue4",lwd=2)
lines(repallhom$Time[274:384], fitted(repallhom_linear)[274:384], col="dodgerblue4",lty=5)
lines(repallhom$Time[274:384], fitted(repallhom_harmonic)[274:384], col="dodgerblue4",lwd=2)
legend(x=0, y=0.9, legend=c("Florida","Comparison States"), col=c("darkorange","dodgerblue4"),lwd = 2)
title(main="Replication: Homicide Rates \nFlorida and Comparison States 1999-2014")

     State     State.Code Year Year.Code Month      Month.Code Deaths
1    Alabama   1          1999 1999      Jan., 1999 1999/01    40
2    Alabama   1          1999 1999      Feb., 1999 1999/02    36
3    Alabama   1          1999 1999      Mar., 1999 1999/03    42
4    Alabama   1          1999 1999      Apr., 1999 1999/04    29
5    Alabama   1          1999 1999      May, 1999  1999/05    43
6    Alabama   1          1999 1999      Jun., 1999 1999/06    31
7    Alabama   1          1999 1999      Jul., 1999 1999/07    36
8    Alabama   1          1999 1999      Aug., 1999 1999/08    40
9    Alabama   1          1999 1999      Sep., 1999 1999/09    40
10   Alabama   1          1999 1999      Oct., 1999 1999/10    28
11   Alabama   1          1999 1999      Nov., 1999 1999/11    34
12   Alabama   1          1999 1999      Dec., 1999 1999/12    43
13   Alabama   1          2000 2000      Jan., 2000 2000/01    30
14   Alabama   1          2000 2000      Feb., 2000 2000/02    28
15   Alabama   1          2000 2000      Mar., 2000 2000/03    30
16   Alabama   1          2000 2000      Apr., 2000 2000/04    23
17   Alabama   1          2000 2000      May, 2000  2000/05    62
18   Alabama   1          2000 2000      Jun., 2000 2000/06    41
19   Alabama   1          2000 2000      Jul., 2000 2000/07    45
20   Alabama   1          2000 2000      Aug., 2000 2000/08    50
21   Alabama   1          2000 2000      Sep., 2000 2000/09    43
22   Alabama   1          2000 2000      Oct., 2000 2000/10    33
23   Alabama   1          2000 2000      Nov., 2000 2000/11    29
24   Alabama   1          2000 2000      Dec., 2000 2000/12    26
25   Alabama   1          2001 2001      Jan., 2001 2001/01    31
26   Alabama   1          2001 2001      Feb., 2001 2001/02    36
27   Alabama   1          2001 2001      Mar., 2001 2001/03    27
28   Alabama   1          2001 2001      Apr., 2001 2001/04    40
29   Alabama   1          2001 2001      May, 2001  2001/05    38
30   Alabama   1          2001 2001      Jun., 2001 2001/06    42
...  ...       ...        ...  ...       ...        ...        ...
6942 Wisconsin 55         2014 2014      Jun., 2014 2014/06    16
6943 Wisconsin 55         2014 2014      Jul., 2014 2014/07    13
6944 Wisconsin 55         2014 2014      Aug., 2014 2014/08    22
6945 Wisconsin 55         2014 2014      Sep., 2014 2014/09    10
6946 Wisconsin 55         2014 2014      Oct., 2014 2014/10    14
6947 Wisconsin 55         2014 2014      Nov., 2014 2014/11    10
6948 Wisconsin 55         2014 2014      Dec., 2014 2014/12    13
6949 Wisconsin 55         2015 2015      Jan., 2015 2015/01    19
6950 Wisconsin 55         2015 2015      Feb., 2015 2015/02    15
6951 Wisconsin 55         2015 2015      Mar., 2015 2015/03    25
6952 Wisconsin 55         2015 2015      Apr., 2015 2015/04    21
6953 Wisconsin 55         2015 2015      May, 2015  2015/05    22
6954 Wisconsin 55         2015 2015      Jun., 2015 2015/06    20
6955 Wisconsin 55         2015 2015      Jul., 2015 2015/07    26
6956 Wisconsin 55         2015 2015      Aug., 2015 2015/08    16
6957 Wisconsin 55         2015 2015      Sep., 2015 2015/09    19
6958 Wisconsin 55         2015 2015      Oct., 2015 2015/10    20
6959 Wisconsin 55         2015 2015      Nov., 2015 2015/11    19
6960 Wisconsin 55         2015 2015      Dec., 2015 2015/12    15
6961 Wisconsin 55         2016 2016      Jan., 2016 2016/01    17
6962 Wisconsin 55         2016 2016      Feb., 2016 2016/02    12
6963 Wisconsin 55         2016 2016      Mar., 2016 2016/03    26
6964 Wisconsin 55         2016 2016      Apr., 2016 2016/04    27
6965 Wisconsin 55         2016 2016      May, 2016  2016/05    20
6966 Wisconsin 55         2016 2016      Jun., 2016 2016/06    18
6967 Wisconsin 55         2016 2016      Jul., 2016 2016/07    25
6968 Wisconsin 55         2016 2016      Aug., 2016 2016/08    28
6969 Wisconsin 55         2016 2016      Sep., 2016 2016/09    21
6970 Wisconsin 55         2016 2016      Oct., 2016 2016/10    28
6971 Wisconsin 55         2016 2016      Dec., 2016 2016/12    26

In [ ]:
#Check Weights
synth.out$solution.w
For your convenience,
| we have already converted the panel
| dataset to a object suitable for running
| the synth() function by using the
| dataprep() function. The output is called
| dataprep.out.
Use the subject dataprep.out and the
| synth() function to identify the weights
| that create the best possible synthetic
| control unit for the treated and assign
| the result to an object called synth.out.
synth.out <- synth(data.prep.obj = dataprep.out)